### ISSUE TITLE
Set Up your Kanban Board

### ISSUE THREAD

**Issue by Diegogagan2587** [Diegogagan2587/Book-a-concert-back-end#9]
# Implemented Kanban

**Team Members:** 3 People

@rudicarrilloypr 
@danifromecuador 
@Diegogagan2587 

 you can review our [Kanban Board here](https://github.com/users/Diegogagan2587/projects/4/views/2)
 
 
![image](https://github.com/Diegogagan2587/Book-a-concert-back-end/assets/61764778/9d8af3c9-75bc-438d-8316-80bbd3daf696)

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
